### ISSUE TITLE
Possible race condition when completing ssl handshake future

### ISSUE THREAD

**Issue by jentfoo** [threadly/litesockets#20]
There is something that looks suspicious to me in SSLClient (and want your feedback):

I see several places in SSLClient where there is an attempt to checking if the handshakeFuture is done, then setting a result or failure based off that status.  This is not sufficient to prevent an IllegalStateException from another thread providing a result (failure or otherwise) after the ifDone state is checked, then set.

Is this an issue, or not because we are expected to be in a single threaded context from the client key?

**Comment by lwahlmeier** [comment]
So that would be correct everything that is happening during the handshake
should be happening on the clients Read thread so technically in a single
threaded context.  I would have to look closer there might be a couple
places were its not but they should be cases we cant get to unless the
sslHandshake got into a bad state and could never complete.

There might be an issue along these lines on the connect Future from the
TCPClient.  Take a look and let me know.  I guess in most cases when I am
needing is a way to set a failure/result atomically so as not having to
lock to complete it.

**Comment by jentfoo** [comment]
FWIW, the 4.0.0 threadly makes this a non-issue anyways:

https://github.com/threadly/litesockets/compare/threadly:master...jentfoo:update_threadly_4.0.0?expand=1

**Comment by jentfoo** [comment]
Closing since this is not an issue, and we are moving to threadly 4.X in 2.1 anyways
