### ISSUE TITLE
4.0.0: Should `SimpleMergedByteBuffers` take in a `readOnly` boolean in the constructor

### ISSUE THREAD

**Issue by jentfoo** [threadly/litesockets#49]
It seems this boolean has no impact on the behavior of the class.  Did you have future plans for this or should we remove it?

**Comment by lwahlmeier** [comment]
Its actually already used in the SSLProcessor, though it specifically has to be set to false.  This flag was only ever added to MergedByteBuffers because of, what I consider a bug in the SSLEngine in java.  I was have all bytebuffers written into a Client object set as read only, and when sslEngine.write was called with a readonly buffer it would throw an exception, which was odd because it should only be reading from the "write" buffer and writing into the encrypted buffer which was not readonly.

I think we should keep it, but I would be fine with having a constructor that defaults it.
